### ISSUE TITLE
Panics at unreachable!() invocation

### ISSUE THREAD

**Issue by K4rakara** [Smithay/client-toolkit#201]
With the latest version of `wayland-protocols` and `sway-git`, the following panic occurs:

Changing line 123 in `environment.rs` to this fixes the panic:

```diff
+queue.sync_roundtrip(&mut (), |_, _, _| ())?;
-queue.sync_roundtrip(&mut (), |_, _, _| unreachable!())?;
```

```
[3417019.706]  -> wl_display@1.get_registry(new id wl_registry@2)
[3417019.773]  -> wl_display@1.sync(new id wl_callback@3)
[3417019.909] wl_display@1.delete_id(3)
[3417019.929] wl_registry@2.global(1, "wl_shm", 1)
[3417019.999]  -> wl_registry@2.bind(1, "wl_shm", 1, new id [unknown]@4)
[3417020.051] wl_registry@2.global(2, "wl_drm", 2)
[3417020.085] wl_registry@2.global(3, "zwp_linux_dmabuf_v1", 3)
[3417020.115] wl_registry@2.global(4, "wl_compositor", 4)
[3417020.150]  -> wl_registry@2.bind(4, "wl_compositor", 4, new id [unknown]@5)
[3417020.199] wl_registry@2.global(5, "wl_subcompositor", 1)
[3417020.236] wl_registry@2.global(6, "wl_data_device_manager", 3)
[3417020.272] wl_registry@2.global(7, "zwlr_gamma_control_manager_v1", 1)
[3417020.304] wl_registry@2.global(8, "zxdg_output_manager_v1", 3)
[3417020.337] wl_registry@2.global(9, "org_kde_kwin_idle", 1)
[3417020.375] wl_registry@2.global(10, "zwp_idle_inhibit_manager_v1", 1)
[3417020.409] wl_registry@2.global(11, "zwlr_layer_shell_v1", 4)
[3417020.445]  -> wl_registry@2.bind(11, "zwlr_layer_shell_v1", 4, new id [unknown]@6)
[3417020.491] wl_registry@2.global(12, "xdg_wm_base", 2)
[3417020.528] wl_registry@2.global(13, "zwp_tablet_manager_v2", 1)
[3417020.561] wl_registry@2.global(14, "org_kde_kwin_server_decoration_manager", 1)
[3417020.594] wl_registry@2.global(15, "zxdg_decoration_manager_v1", 1)
[3417020.628] wl_registry@2.global(16, "zwp_relative_pointer_manager_v1", 1)
[3417020.662] wl_registry@2.global(17, "zwp_pointer_constraints_v1", 1)
[3417020.698] wl_registry@2.global(18, "wp_presentation", 1)
[3417020.733] wl_registry@2.global(19, "zwlr_output_manager_v1", 2)
[3417020.766] wl_registry@2.global(20, "zwlr_output_power_manager_v1", 1)
[3417020.799] wl_registry@2.global(21, "zwp_input_method_manager_v2", 1)
[3417020.833] wl_registry@2.global(22, "zwp_text_input_manager_v3", 1)
[3417020.868] wl_registry@2.global(23, "zwlr_foreign_toplevel_manager_v1", 3)
[3417020.903] wl_registry@2.global(24, "zwlr_export_dmabuf_manager_v1", 1)
[3417020.938] wl_registry@2.global(25, "zwlr_screencopy_manager_v1", 3)
[3417020.972] wl_registry@2.global(26, "zwlr_data_control_manager_v1", 2)
[3417021.004] wl_registry@2.global(27, "zwp_primary_selection_device_manager_v1", 1)
[3417021.038] wl_registry@2.global(28, "wp_viewporter", 1)
[3417021.069] wl_registry@2.global(29, "zxdg_exporter_v1", 1)
[3417021.104] wl_registry@2.global(30, "zxdg_importer_v1", 1)
[3417021.140] wl_registry@2.global(31, "zxdg_exporter_v2", 1)
[3417021.172] wl_registry@2.global(32, "zxdg_importer_v2", 1)
[3417021.204] wl_registry@2.global(33, "xdg_activation_v1", 1)
[3417021.241] wl_registry@2.global(34, "zwp_virtual_keyboard_manager_v1", 1)
[3417021.276] wl_registry@2.global(35, "zwlr_virtual_pointer_manager_v1", 2)
[3417021.310] wl_registry@2.global(36, "zwlr_input_inhibit_manager_v1", 1)
[3417021.344] wl_registry@2.global(37, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[3417021.378] wl_registry@2.global(38, "wl_seat", 7)
[3417021.411] wl_registry@2.global(39, "zwp_pointer_gestures_v1", 1)
[3417021.442] wl_registry@2.global(43, "wl_output", 3)
[3417021.478]  -> wl_registry@2.bind(43, "wl_output", 3, new id [unknown]@7)
[3417021.540] wl_registry@2.global(44, "wl_output", 3)
[3417021.580]  -> wl_registry@2.bind(44, "wl_output", 3, new id [unknown]@8)
[3417021.638] wl_callback@3.done(42133)
[3417021.661]  -> wl_display@1.sync(new id wl_callback@3)
[3417021.804] wl_display@1.delete_id(3)
[3417021.835] wl_shm@4.format(0)
thread 'main' panicked at 'internal error: entered unreachable code', /home/jack/.opt/cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.15.1/src/environment.rs:123:49
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fdf65053e99e8966f9bd83b5a8491326cb33d638/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/fdf65053e99e8966f9bd83b5a8491326cb33d638/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at /rustc/fdf65053e99e8966f9bd83b5a8491326cb33d638/library/core/src/panicking.rs:50:5
   3: smithay_client_toolkit::environment::Environment<E>::new::{{closure}}
             at /home/jack/.opt/cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.15.1/src/environment.rs:123:49
   4: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/fdf65053e99e8966f9bd83b5a8491326cb33d638/library/core/src/ops/function.rs:269:13
   5: wayland_client::imp::proxy::proxy_dispatcher::{{closure}}::{{closure}}
             at /home/jack/.opt/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.0/src/native_lib/proxy.rs:429:25
   6: scoped_tls::ScopedKey<T>::with
             at /home/jack/.opt/cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:171:13
   7: wayland_client::imp::proxy::proxy_dispatcher::{{closure}}
             at /home/jack/.opt/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.0/src/native_lib/proxy.rs:426:21
   8: std::panicking::try::do_call
             at /rustc/fdf65053e99e8966f9bd83b5a8491326cb33d638/library/std/src/panicking.rs:403:40
   9: __rust_try
  10: std::panicking::try
             at /rustc/fdf65053e99e8966f9bd83b5a8491326cb33d638/library/std/src/panicking.rs:367:19
  11: std::panic::catch_unwind
             at /rustc/fdf65053e99e8966f9bd83b5a8491326cb33d638/library/std/src/panic.rs:129:14
  12: wayland_client::imp::proxy::proxy_dispatcher
             at /home/jack/.opt/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.0/src/native_lib/proxy.rs:387:15
  13: <unknown>
  14: <unknown>
  15: wl_display_dispatch_queue_pending
  16: wl_display_roundtrip_queue
  17: wayland_client::imp::event_queue::EventQueueInner::sync_roundtrip::{{closure}}
             at /home/jack/.opt/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.0/src/native_lib/event_queue.rs:85:17
  18: wayland_client::imp::event_queue::with_dispatch_meta::{{closure}}
             at /home/jack/.opt/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.0/src/native_lib/event_queue.rs:24:57
  19: scoped_tls::ScopedKey<T>::set
             at /home/jack/.opt/cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  20: wayland_client::imp::event_queue::with_dispatch_meta
             at /home/jack/.opt/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.0/src/native_lib/event_queue.rs:24:5
  21: wayland_client::imp::event_queue::EventQueueInner::sync_roundtrip
             at /home/jack/.opt/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.0/src/native_lib/event_queue.rs:83:9
  22: wayland_client::event_queue::EventQueue::sync_roundtrip
             at /home/jack/.opt/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.29.0/src/event_queue.rs:203:9
  23: smithay_client_toolkit::environment::Environment<E>::new
             at /home/jack/.opt/cargo/registry/src/github.com-1ecc6299db9ec823/smithay-client-toolkit-0.15.1/src/environment.rs:123:9
  24: notbar::main
             at ./src/main.rs:52:23
  25: core::ops::function::FnOnce::call_once
             at /rustc/fdf65053e99e8966f9bd83b5a8491326cb33d638/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[wayland-client error] A handler for wl_shm panicked.
zsh: abort (core dumped)  WAYLAND_DEBUG=1 RUST_BACKTRACE=1 cargo run
```

**Comment by K4rakara** [comment]
Not a bug-- panic caused by an object with no handler. A nicer panic message would be nice though.
